### ISSUE TITLE
Seeking help with getting a self-hosted Ding going

### ISSUE THREAD

**Issue by ScottChesworth** [Flameborn/ding.ga#2]
Hi, thanks for publishing this! I've been looking for an accessible in-browser chat to accompany some live streams and Ding seems like just the right fit. 
Been running into an issue trying to get it running on my buddy @timtam's Linux server though, hoping you can share some advice?

He tried to build his own Dockerfile first. That didn't work, so he tried to run it step by step as per the ReadMe. When that didn't work either, he tried using an older node version, figured this was worth a shot since the last commit was from 2021.
He doesn't get any errors, but he can't connect when running it on the server.

Any ideas appreciated. Thanks in advance.

**Comment by Timtam** [comment]
Just adding here, I don't get any errors in the logs either, I tried connecting to 1844, tried mapping the port and forwarding it via Traefik too, but no luck whatsoever.

**Comment by Flameborn** [comment]
Hi @ScottChesworth and @Timtam

Thanks for reporting this.

I've used Node v19.4.0 to install a fresh copy and, following the readme, everything works as expected.

When you start ding via *npm start*, do you see the log print that it is listening on port 1844?

Let's make sure that Ding is indeed listening. Try:

```
curl localhost:1844
```

Or alternatively:

```
sudo lsof -i:1844
```

You might have to install lsof if you haven't already.

If the output shows a html page, or in the case of lsof a Node process, then the server is indeed up and listening.

You should proxy 127.0.0.1 port 1844 to be able to connect via a different machine.

Hope this helps.

**Comment by Timtam** [comment]
Hi @Flameborn,

thanks. I can indeed confirm that the server is running on the machine, I just cannot connect from the outside (yet). I however want to use it behind a Traefik reverse proxy if possible. Last time I tried I wasn't able to reach the server though. Is there any other port involved other than 1844 that I need to have accessible to the app to work, or is it just 1844? And is the port hardcoded in some way so that I cannot actually reverse them, like i'm mapping the port to 80 when accessing it from the outside, so 1844 won't work when trying to reach the app that way.

**Comment by Timtam** [comment]
This is my Dockerfile. Building and running that shows that my port is open, but the connection gets reset as soon as I try to connect:
```
FROM node:19 AS BUILD_IMAGE

RUN curl -sf https://gobinaries.com/tj/node-prune | sh

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./public /app/public
COPY ./templates /app/templates

RUN npm install && npm install pug-cli -g && pug templates --out /app/public

# remove development dependencies
RUN npm prune --production

# run node prune
RUN /usr/local/bin/node-prune

FROM node:19-alpine

EXPOSE 1844

WORKDIR /app

# copy from build image
COPY --from=BUILD_IMAGE /app/public ./public
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY ./server.js /app/server.js
COPY ./chat-anarchy-mediabot /app/chat-anarchy-mediabot
COPY ./chat-anarchy-server /app/chat-anarchy-server
COPY ./chat-anarchy-whobot /app/chat-anarchy-whobot
COPY ./ding-8ball /app/ding-8ball
COPY ./ding-coin /app/ding-coin
COPY ./ding-dic /app/ding-dic
COPY ./ding-dice /app/ding-dice
COPY ./package.json /app/package.json

CMD npm start
```

```
root@vps46689:~# lsof -i:1844                                                                                           
COMMAND       PID USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME                                                        
docker-pr 3747875 root    4u  IPv4 2043367055      0t0  TCP *:1844 (LISTEN)                                             
docker-pr 3747882 root    4u  IPv6 2043367058      0t0  TCP *:1844 (LISTEN)                                             
root@vps46689:~# curl localhost:1844                                                                                    
curl: (56) Recv failure: Connection reset by peer                                                                       
```

**Comment by Flameborn** [comment]
This is because your Dockerfile's expose line only exposes port 1844 for inter-container communication only, it is not exposed to your host.

To expose ports from within a Docker image, you need to use -p or --expose. For example:

```
docker run -p 127.0.0.1:1844:1844/tcp ding
```

This should expose your container port to the host machine, so the curl command I mentioned above can return a html page. You will be able to proxy it for your web server as well.

**Comment by Timtam** [comment]
That is what I did and it doesn't work:
```
root@vps46689:~/ding.ga# docker run -p 127.0.0.1:1844:1844/tcp -d --rm ding.ga                                          
003bfad5c3dab38d23f985ebbc3843563e0b32023ea1d85b5e0d7e6e3827868b                                                        
root@vps46689:~/ding.ga# docker logs 003b                                                                               
                                                                                                                        
> chat-anarchy@2.0.0 start                                                                                              
> node server.js                                                                                                        
                                                                                                                        
Ding! is listening on port 1844                                                                                         
root@vps46689:~/ding.ga# curl localhost:1844                                                                            
curl: (56) Recv failure: Connection reset by peer                                                                       
root@vps46689:~/ding.ga# lsof -i:1844                                                                                   
COMMAND      PID USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME                                                         
docker-pr 565202 root    4u  IPv4 2054671165      0t0  TCP localhost:1844 (LISTEN)                                      
```
Something weird seems to be going on.

**Comment by Flameborn** [comment]
It seems like it. What happens if you open a shell within the container and try curl (if you have it installed within the image) that way? E.g.:

```
sudo docker exec ding /bin/sh
curl 127.0.0.1:1844
```

Do you have defined iptables (or UFW) rules that might block Docker containers?

I can't really think of anything else at the moment, but if I get the chance I'm going to try and build a docker image to see if it works on my end.

**Comment by Timtam** [comment]
The docker container doesn't have curl installed as it seems, as I cannot run it within the container. I don't have any firewall blocking container ports though, i'm running several other web apps the very same way in separate docker containers and all of them work just fine. I don't know what the actual problem is here TBH.

**Comment by Timtam** [comment]
Here we go, issue solved. The default IP address in the server.js is 127.0.0.1. That IP doesn't work inside docker containers, you need to listen on 0.0.0.0 due to how the networking works inside Docker. Either rewrite the ip within the server.js to 0.0.0.0 or set the IP env variable to that string and it works just fine.
Thank you for the help anyway!

**Comment by Flameborn** [comment]
Ah, makes sense.

I suggest using an environment variable, as modifying *server.js* for normal setups is not ideal.

I'm happy you got it to work!
