### ISSUE TITLE
Is there a way to prompt users to choose a nick when joining the chat?

### ISSUE THREAD

**Issue by ScottChesworth** [Flameborn/ding.ga#3]
Hi, just doing some customizations here for a self-hosted Ding. I'm looking for a way to prompt users to enter a nick when they join the chat. Is that possible? Any tips appreciated.

**Comment by Flameborn** [comment]
Hello,

Due to the anonymous nature of Ding, this is not possible, nor it's something that I could see added in the future, sorry.

However, you could replace the *welcome* function for the welcome event in *ding.js*, which prompts the user via a simple input box for a nickname. If the result is not empty, send it on via a simulated */nick* command, otherwise prompt again.

It's not the prettiest way to do it, as ideally a form is better, but as a quick hack it will work.

Something like this:

```
function welcome(data) {
	username = prompt("Please enter your nick name:", "");
	while (!username) {
		username = prompt("Please enter your nick name:", "");
	}
socket.send("/nick "+username);
}
```

I am closing this, but please feel free to comment if you have further questions.

**Comment by ScottChesworth** [comment]
Thanks much, I'll try that.
